In [ ]:
### 6/23/19: WORKING! ###

### Fully general formula

def full_formula_2(m, n, top, bottom, left, right):
  from math import factorial as f
  
  left_trees = []
  for p in range(0, len(left)):
    left_trees += left[p]
    
  right_trees = []
  for q in range(0, len(right)):
    right_trees += right[q]
  
  all_trees = top[0] + bottom[0] + left_trees + right_trees
  
  seqs_01 = all_seqs(m + n, m)
  vert_seqs = all_seqs_2(seqs_01, left, right) 
     
  top_vert = sum(len(TP) for TP in top[0])
     
  w = m + n + 2 + sum([len(T) for T in all_trees])
  
  phi = seq_mult([ord_num_tree(T)/f(len(T)) for T in all_trees]) * \
     sum([f(w - 1) * seq_mult([1/(w - (i + 1) - top_vert - \
                                 sum([seq[j] for j in range(0, i)])) for \
                              i in range(0, m + n + 1)]) for seq in vert_seqs])
     
  return(phi)

### All of the m + n choose n sequences of m 0's and n 1's

def all_seqs(m, n):
  ab_seqs = []
  a_seqs = delete(list(range(1, m + 1)), n, 0, [])
  for x in a_seqs:
    AB_list = [0]*m
    for i in range(1, m + 1):
      if i in x:
        AB_list[i - 1] = 0
      else:
        AB_list[i - 1] = 1
    ab_seqs += [AB_list]
  return(ab_seqs)

### Needed by all_seqs

def delete(x, m, i, a_pos_seqs):
  if len(x) == m:
    A_list = x
    a_pos_seqs += [A_list]
  else:
    for j in range(i, len(x)):
      A_list = delete(x[0:j] + x[j + 1: len(x)], m, j, a_pos_seqs)
  return(a_pos_seqs)

### Converts a 01 sequence to a sequence of tree vertx set cardinalities

def all_seqs_2(seqs_list, left, right):
  import numpy as np
  n = len(left) + len(right)
  H = np.zeros((len(seqs_list), n), dtype = int)
  for seq in seqs_list:
    row = seqs_list.index(seq)
    lk = 0
    rk = 0
    for j in range(0, len(seq)):
      if seq[j] == 0:
        H[row, j] = sum([len(S) for S in left[lk]])
        lk += 1
      else:
        H[row, j] = sum([len(S) for S in right[rk]])
        rk += 1
  return(H)

### Multiply the elements in a sequence.  Needed by full_formula_2.

def seq_mult(s):
  pr = 1
  for i in range(0, len(s)):
    pr *= s[i]
  return(pr)

### Manually enter a graph.  Useful for entering the trees.

def graph_entry(n):
  import numpy as np
  A = np.zeros((n, n), dtype = int)
  while True:
    citation = input("Enter row-column separated by space. Enter s to stop.")
    if citation == 's':
      break
    else:
      citation = [int(x) for x in citation.split(' ')]
      A[citation[0] - 1, citation[1] - 1] = 1
  return(A)

### Computes the order number of any network.  Very slow.

def order_number(A):
  import numpy as np
  count = 0
  if np.shape(A)[0] == 1:
    count = 1
  else:
    for i in range(0, np.shape(A)[0]):
      if np.all(A[i] == 0):
        B = np.delete(A, i, axis = 0)
        C = np.delete(B, i, axis = 1)
        count = count + order_number(C)
  return count

### Quickly computes the order number of any tree.  Needed by full_formula_2.

def ord_num_tree(T):
  import numpy as np
  from math import factorial
  n = len(T)
  S = T
  B = branch_nums(S)
  for i in range(0, n):
    for j in range(0, n):
      if S[j, i] == 1:
        S[j,i] = S[j,i] + np.sum(B[:, j])
  D = np.zeros((n, n), dtype = int)
  for k in range(0, n):
    for l in range(0, n):
      D[l, k] = factorial(S[l, k])
  count = 1
  for p in range(0, n):
    count = count * factorial(np.sum(S[:, p])) / np.product(D[:, p])
  return int(count)


### Needed by ord_num_tree

def branch_nums(T):
  import numpy as np
  from numpy.linalg import matrix_power
  n = len(T)
  B = np.zeros((n, n), dtype = int)
  i = 1
  while True:
    B = B + matrix_power(T, i)
    i += 1
    if np.all(matrix_power(T, i) == np.zeros((n, n))):
      break
  return(B)


### m choose n (not actually needed)

def comb(m, n):
  from math import factorial
  if m < n:
    answer = 0
  else:
    answer = int(factorial(m) / (factorial(n) * factorial(m - n)))
  return answer

In [ ]:
import time

In [ ]:
G = graph_entry(15)

Enter row-column separated by space. Enter s to stop.4 1
Enter row-column separated by space. Enter s to stop.5 1
Enter row-column separated by space. Enter s to stop.5 2
Enter row-column separated by space. Enter s to stop.6 3
Enter row-column separated by space. Enter s to stop.7 3
Enter row-column separated by space. Enter s to stop.8 3
Enter row-column separated by space. Enter s to stop.9 4
Enter row-column separated by space. Enter s to stop.9 1
Enter row-column separated by space. Enter s to stop.9 5
Enter row-column separated by space. Enter s to stop.10 2
Enter row-column separated by space. Enter s to stop.10 6
Enter row-column separated by space. Enter s to stop.11 7
Enter row-column separated by space. Enter s to stop.11 8
Enter row-column separated by space. Enter s to stop.12 8
Enter row-column separated by space. Enter s to stop.13 9
Enter row-column separated by space. Enter s to stop.14 9
Enter row-column separated by space. Enter s to stop.14 10
Enter row-column separ

In [ ]:
print(G)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]]


In [ ]:
start = time.clock()
p = order_number(G)
print(time.clock() - start, "seconds")
print(p)

348.5528559999998 seconds
8241100


In [ ]:
348.55/60

5.809166666666667

In [ ]:
T1 = graph_entry(3)

Enter row-column separated by space. Enter s to stop.2 1
Enter row-column separated by space. Enter s to stop.3 1
Enter row-column separated by space. Enter s to stop.s


In [ ]:
T_2 = graph_entry(5)

Enter row-column separated by space. Enter s to stop.2 1
Enter row-column separated by space. Enter s to stop.3 1
Enter row-column separated by space. Enter s to stop.4 3
Enter row-column separated by space. Enter s to stop.5 3
Enter row-column separated by space. Enter s to stop.s


In [ ]:
full_formula_2(2, 1, [[T1]], [[]], [[],[T_2]], [[T1, T_2]])

2334717665279.9995

In [ ]:
################################################################################
################################################################################

In [ ]:
# Not needed.

def seq_read(AB, left_connect, right_connect, left_vert, right_vert):
  l_count = 0
  r_count = 0
  j = 0
  LR_seq = [0]*(len(left_connect) + len(right_connect))
  spot_seq = [0]*(len(left_connect) + len(right_connect))
  for i in range(0, len(AB)):
    if AB[i] == 'a':
      l_count += 1
    else:
      r_count += 1
    if l_count in left_connect:
      spot_seq[j] = i + 1
      LR_seq[j] = left_vert[0]
      left_vert = left_vert[1:]
      left_connect = left_connect[1:]
      j += 1
    if r_count in right_connect:
      spot_seq[j] = i + 1
      LR_seq[j] = right_vert[0]
      right_vert = right_vert[1:]
      right_connect = right_connect[1:]
      j += 1
  return(spot_seq, LR_seq)

In [ ]:
# Not needed.

def full_formula(m, n, left_trees, right_trees, left_connect, right_connect):
  
  from math import factorial as f
  
  left_vert = [len(LT) for LT in left_trees]
  right_vert = [len(RT) for RT in right_trees]
  vl = sum(lv for lv in left_vert)
  vr = sum(rv for rv in right_vert)
  w = m + n + 1 + vl + vr
  
  seqs = all_seqs(m, n)
  
  combs = 0
  
  for AB_list in seqs:
    spot_seq, LR_seq = seq_read(AB_list, left_connect, right_connect, left_vert, right_vert)
    data = list(zip(spot_seq, LR_seq))
    prod = f(w - data[0][0])/np.prod([f(v) for v in LR_seq])
    for pair in data[1:]:
      i = data.index(pair)
      prod *= f(m + n + 1 + sum(LR_seq[i:]) - pair[0])
    combs += prod
    
  phi_trees = [ord_num_tree(T) for T in left_trees + right_trees]
  
  phi = np.prod(phi_trees) * combs
  
  return(combs)

In [ ]:
# Enter the incidence matrix for an n-vertex graph.

def graph_entry(n):
  import numpy as np
  A = np.zeros((n, n), dtype = int)
  while True:
    citation = input("Enter row-column separated by space. Enter s to stop.")
    if citation == 's':
      break
    else:
      citation = [int(x) for x in citation.split(' ')]
      A[citation[0] - 1, citation[1] - 1] = 1
  return(A)


# Check that 'formula' computes the correct value.

def compare2(T, m, n, i):
  A = build(T, m, n, i)
  return order_number(A) == formula(T, m, n, i)


# Build the DAG with center loop L(m, n), left trees connecting at the
# entries of left_connect, and right trees connecting at the entries of
# right_connect.

def build(left_trees, right_trees, m, n, left_connect, right_connect):
  
  import numpy as np
  
  left = list(zip(left_trees, left_connect))
  right = list(zip(right_trees, right_connect))
  
  left_v = [0]*(len(left))
  right_v = [0]*(len(right))
  
  for i in range(0, len(left_v)):
    left_v[i] = len(left_trees[i])
  
  for i in range(0, len(right_v)):
    right_v[i] = len(right_trees[i])
    
  v = sum(left_v) + sum(right_v)
  
  A = np.zeros((v + m + n + 2, v + m + n + 2), dtype = int)
  start = 0
  
  for T, c in left:
    A[start : start + len(T), start : start + len(T)] = T
    A[start, v + c] = 1
    start += len(T)
    
  for T, c in right:
    A[start : start + len(T), start : start + len(T)] = T
    A[start, v + m + c] = 1
    start += len(T)
    
  for i in range(0, m):
    A[v + 1 + i, v + i] = 1
  A[v + m + 1, v] = 1
  for j in range(1, n + 1):
    A[v + m + 1 + j, v + m + j] = 1
  A[v + m + n + 1, v + m] = 1
  return (A)


# Computes the order number of any DAG, but is very slow once the number of vertices gets near 20.

def order_number(A):
  import numpy as np
  count = 0
  if np.shape(A)[0] == 1:
    count = 1
  else:
    for i in range(0, np.shape(A)[0]):
      if np.all(A[i] == 0):
        B = np.delete(A, i, axis = 0)
        C = np.delete(B, i, axis = 1)
        count = count + order_number(C)
  return count


# Formula for computing the order number of T*(m, n, i).

def formula(T, m, n, i):
  phi = ord_num_tree(T)
  v = len(T)
  return phi*(comb(v + m - i + 1, v) * sum(comb(n + i - j - 1, i - j) for j in range(1, i + 1)) +
         sum(comb(n + i - k - 1, n - k) * comb(m - i + k, m - i) * comb(v + m - i + k + 1, v) for k in range(1, n + 1)))


# Order number of trees.

def ord_num_tree(T):
  import numpy as np
  from math import factorial
  n = len(T)
  S = T
  B = branch_nums(S)
  for i in range(0, n):
    for j in range(0, n):
      if S[j, i] == 1:
        S[j,i] = S[j,i] + np.sum(B[:, j])
  D = np.zeros((n, n), dtype = int)
  for k in range(0, n):
    for l in range(0, n):
      D[l, k] = factorial(S[l, k])
  count = 1
  for p in range(0, n):
    count = count * factorial(np.sum(S[:, p])) / np.product(D[:, p])
  return int(count)


# Needed by ord_num_tree

def branch_nums(T):
  import numpy as np
  from numpy.linalg import matrix_power
  n = len(T)
  B = np.zeros((n, n), dtype = int)
  i = 1
  while True:
    B = B + matrix_power(T, i)
    i += 1
    if np.all(matrix_power(T, i) == np.zeros((n, n))):
      break
  return(B)


# m choose n

def comb(m, n):
  from math import factorial
  if m < n:
    answer = 0
  else:
    answer = int(factorial(m) / (factorial(n) * factorial(m - n)))
  return answer


# Order number for L(m, n) with trees hanging off.

def loop_with_trees(m, n, left_trees, right_trees, left_connect, right_connect):
  
  left_empty = False
  if left_trees == []:
    left_empty = True
  right_empty = False
  if right_trees == []:
    right_empty = True
  
  if left_empty and right_empty:
    phi = comb(m + n, n)
  
  else:
    if not left_empty:
      phi_L1 = ord_num_tree(left_trees[0])
      l1 = left_connect[0]
      v_l1 = len(left_trees[0])
    else:
      phi_L1 = 0
      l1 = m + 1
      v_l1 = 0
      
    if not right_empty:
      phi_R1 = ord_num_tree(right_trees[0])
      r1 = right_connect[0]
      v_r1 = len(right_trees[0])
    else:
      phi_R1 = 0
      r1 = n + 1
      v_r1 = 0
      
    v = sum(len(L) for L in left_trees) + sum(len(R) for R in right_trees)
    
    print(phi_L1, l1, v_l1, phi_R1, r1, v_r1)
    print(v)
   
    phi = phi_L1 * sum(comb(l1 + k - 2, k - 1) * comb(v + m - l1 + n - k + 2, v_l1) *
                      loop_with_trees(m - l1, n - k + 1, left_trees[1:], right_trees, 
                                     [l - l1 for l in left_connect][1:], 
                                     [r - k + 1 for r in right_connect]) 
                       for k in range(1, r1 + 1)) + \
          phi_R1 * sum(comb(r1 + k - 2, k - 1) * comb(v + m - r1 + n - k + 2, v_r1) *
                      loop_with_trees(m - k + 1, n - r1, left_trees, right_trees[1:],
                                     [l - k + 1 for l in left_connect],
                                     [r - r1 for r in right_connect][1:])
                       for k in range(1, l1 + 1))
      
  return phi
    

In [ ]:
################################################################################
################################################################################

In [ ]:
T = graph_entry(5)

In [ ]:
# AGREES! (This is ([T, T], 3, 2, 2, 3))

8*formula(T, 1, 2, 1)*comb(14,5) + 2*(8*formula(T, 1, 1, 1)*comb(13,5)) + 8*48*comb(12,5) + 2*8*48*comb(12,5)

In [ ]:
import time
start = time.clock()
###
print(time.clock() - start, "seconds")

In [ ]:
compare2(T, 1, 2, 1)

In [ ]:
for q in range(1, 6):
  for r in range(1, 6):
    for s in range(1, q + 1):
      print(q, ", ", r, ", ", s, ":", compare2(T, q, r, s))

In [ ]:
################################################################################
################################################################################

In [ ]:
# Returns entire list of component triples in decomposition.

def split(indices):
  from operator import add
  split_list = []
  for i in range(0, len(indices)):
    if 0 in indices[i]:
      split_list = split_list + [indices[i]]
    else:
      split_list = split_list + split([list(map(add, indices[i], [-1, 0, -1])), list(map(add, indices[i], [0, -1, 0]))])
  return split_list

In [ ]:
# Formula for counting all component triples.

def formula(indices):
  from math import factorial
  n = indices[0][1]
  i = indices[0][2]
  return int(factorial(n + i)/(factorial(n)*factorial(i)))

In [ ]:
# Checks whether formula agrees with actual number of triples.

def compare(indices):
  return len(split(indices)) == formula(indices)